---
# tasks file for memcached

# Setup/install tasks
- name: Install Memcached
  apt:
    name: memcached
    state: latest
  register: memcached_install

# Configure Memcached
- name: Copy Memcached configuration
  template:
    src: memcached.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Ensure Memcached is started and set to run on startup
  service:
    name: memcached
    state: started
    enabled: yes

###

- name: Install Memcached
  apt: pkg=memcached state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: "Ensure Memcached is {{ memcached.start | ternary('started','stopped') }}"
  service: name=memcached state={{ memcached.start | ternary('restarted','stopped') }} enabled={{ memcached.service_enabled }}
