---
# handlers file for memcached

- name: restart memcached
  service: name=memcached state=restarted
  when: not memcached_install.changed

- name: Restart Memcached
  service: name=memcached state=restarted
